### ISSUE TITLE
Import instructions don't appear to work on node 19.4

### ISSUE THREAD

**Issue by rgarner** [sprout2000/esbuild-copy-plugin#2]
When I `import { copyPlugin } from '@sprout2000/esbuild-copy-plugin';` as per the README, I get 

```
import { copyPlugin } from '@sprout2000/esbuild-copy-plugin';
         ^^^^^^^^^^
SyntaxError: Named export 'copyPlugin' not found. The requested module '@sprout2000/esbuild-copy-plugin' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@sprout2000/esbuild-copy-plugin';
const { copyPlugin } = pkg;
```

The second form does indeed work as suggested. This is in a script executed via `node esbuild.config.js` which is defined as `"type": "module"` in `package.json`. Is there something I'm failing to do?

**Comment by sprout2000** [comment]
@rgarner 
If you are writing esbuild scripts in vanilla JS, you must import this module using the `require` statement.

```js
const { copyPlugin } = require("@sprout2000/esbuild-copy-plugin");
```

This would eliminate the need to set `"type": "module"` in `package.json`.

If you are writing scripts in native ESM, the suggestions are correct, because this module does not directly support native ESM.

best regards.

**Comment by rgarner** [comment]
I'm writing in ESM in order to have native `await` access for esbuild; I slightly prefer `"type": "module"` over the `.mjs` extension. Thank you! I shall stop worrying about it.
